title: Rachel Kidwell # your name (or website title) here
logo: "RachelKidwell00/RachelKidwell00.github.io/images/profile" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  UMBC class of 2022
  <br><br>
  Environmental Science and Geography B.S.
  Geographic Information Science Certificate
  
theme: jekyll-theme-minimal

